name: Comment on PR
on:
  workflow_run:
    workflows: ["Test Workflow"]
    types: [completed]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Download PR Number
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: runtests.yml
          workflow_conclusion: success
          name: pr_number

      - name: Read PR Number
        id: pr_number_reader
        run: echo "pr_number=$(cat pr_number.txt)" >> $GITHUB_ENV

      - name: Show PR Number
        run: echo "PR Number ${{ env.pr_number }}"

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ env.pr_number }}
          body: |
            ⚠️ **PPE Exploit Test**
            - PR Number: ${{ env.pr_number }}
            - `uname -a`: $(uname -a)
