name: Run sipify

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
  push:
    branches:
      - master
      - release-*

jobs:
  sipify:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: run sipify
        run: ./scripts/sipify_all.sh -m

      
