name: Run sipify

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
  push:
    branches:
      - master
      - release-*

jobs:
  sipify:
    if: github.event_name != 'issue_comment' ||github.event.comment.body == '/sipify' )
    runs-on: [ubuntu-latest]
    steps:

      
      - name: run sipify
        run: ./scripts/sipify_all.sh -m

      
