name: Test Workflow
on: pull_request  # Chạy khi có PR

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test script
        run: |
          echo "Running tests..."
          echo "1234" > pr_number.txt

      - name: Upload PR Number Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr_number.txt
