name: Vulnerable Workflow

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Branch Name
        run: |
          echo "Branch Name: ${{ github.ref }}"
          echo ref="${{ github.ref }}" >> $GITHUB_OUTPUT
